### ISSUE TITLE
Network configuration with netplan fails in Packet environment

### ISSUE THREAD

**Issue by gauravgahlot** [tinkerbell/tink#208]
## Expected Behaviour
The network configuration with netplan should complete without an error.

## Current Behaviour
Currently, the network configuration fails with the following error:
```
root@iad2-c2:~/tink# ./generate-envrc.sh enp5s0f1 > envrc
root@iad2-c2:~/tink# source envrc 
root@iad2-c2:~/tink# ./setup.sh 
INFO: starting tinkerbell stack setup
INFO: verifying prerequisites for ubuntu (18.04)
       Found prerequisite: docker
       Found prerequisite: docker-compose
       Found prerequisite: ip
       Found prerequisite: jq
       Found prerequisite: netplan
Traceback (most recent call last):
  File "/usr/sbin/netplan", line 23, in <module>
    netplan.main()
  File "/usr/share/netplan/netplan/cli/core.py", line 50, in main
    self.run_command()
  File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command
    self.func()
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 43, in run
    self.run_command()
  File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command
    self.func()
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 106, in command_apply
    stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/bond0:0']' returned non-zero exit status 4.
root@iad2-c2:~/tink# packet_write_wait: Connection to 147.75.63.50 port 22: Broken pipe

```

## Possible Solution
- This seems to be a bug with netplan discussed [here](https://bugs.launchpad.net/netplan/+bug/1810043). 
- Adding a step to install netplan.io fixes the problem. 
```
apt install -y netplan.io
```

## Steps to Reproduce (for bugs)
- Create a server in Packet environment and change the network type to Hybrid.
- Connect to the server, install git, and clone tink repository.
- Install docker, and docker-compose. 
- Generate envrc with `./generate-envrc.sh enp5s0f1 > envrc` (replace the interface name).
- Run set script `./setup.sh`

## Your Environment
Packet environment with:
- Ubuntu 18.04
- Class - c2.medium.x86 
- Facility - Ashburn (IAD2)

**Comment by gauravgahlot** [comment]
Netplan fixed it and it will be rolled to newest distributions. Also, the problem is now documented in this issue and it has a solution that I hope will help the community.

Closing this issue.
