### ISSUE TITLE
tink GRPC client panics on bad TINKERBELL_CERT_URL

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#324]
## Expected Behaviour

Tink should gracefully return error if it's not able to initialize the client.

## Current Behaviour

Tink panics on bad `TINKERBELL_CERT_URL` environment variable.

## Steps to Reproduce (for bugs)

With CLI on latest master (a6863366fb814600f83c38146e27d7d2708a8bdf):
```sh
0 ✓ (97.6ms) 00:42:48 invidian@dellxps15mateusz ~/repos/kinvolk/tink (master)*$ TINKERBELL_CERT_URL=http://10.17.3.2:42114/cert TINKERBELL_GRPC_AUTHORITY=10.17.3.2:42113 ./tink-cli hardware list
+----+-------------+------------+----------+
| ID | MAC ADDRESS | IP ADDRESS | HOSTNAME |
+----+-------------+------------+----------+
+----+-------------+------------+----------+
0 ✓ (56.7ms) 00:42:51 invidian@dellxps15mateusz ~/repos/kinvolk/tink (master)*$ TINKERBELL_CERT_URL=http://10.17.3.2:42114/ceert TINKERBELL_GRPC_AUTHORITY=10.17.3.2:42113 ./tink-cli hardware list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b0 pc=0x9d1157]

goroutine 1 [running]:
google.golang.org/grpc.(*ClientConn).NewStream(0x0, 0xcaec80, 0xc00019a010, 0x10a34e0, 0xbf18b4, 0x3f, 0x0, 0x0, 0x0, 0x0, ...)
        /home/invidian/go/pkg/mod/google.golang.org/grpc@v1.29.1/stream.go:144 +0x37
github.com/tinkerbell/tink/protos/hardware.(*hardwareServiceClient).All(0xc000010028, 0xcaec80, 0xc00019a010, 0xc00063c120, 0x0, 0x0, 0x0, 0xc000334360, 0xc00053fd70, 0x5d3af7, ...)
        /home/invidian/repos/kinvolk/tink/protos/hardware/hardware.pb.go:824 +0xb5
github.com/tinkerbell/tink/cmd/tink-cli/cmd/hardware.glob..func1(0x10a9b40, 0x10f12c0, 0x0, 0x0)
        /home/invidian/repos/kinvolk/tink/cmd/tink-cli/cmd/hardware/all.go:25 +0x162
github.com/spf13/cobra.(*Command).execute(0x10a9b40, 0x10f12c0, 0x0, 0x0, 0x10a9b40, 0x10f12c0)
        /home/invidian/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x10a9360, 0xc000000180, 0xc00053ff78, 0x407ea5)
        /home/invidian/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/invidian/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tinkerbell/tink/cmd/tink-cli/cmd.Execute(...)
        /home/invidian/repos/kinvolk/tink/cmd/tink-cli/cmd/root.go:34
main.main()
        /home/invidian/repos/kinvolk/tink/cmd/tink-cli/main.go:14 +0x65
```

With unit tests:
```go
$ cat foo/foo_test.go
package main

import (
        "context"
        "os"
        "testing"

        "github.com/tinkerbell/tink/client"
        "github.com/tinkerbell/tink/protos/hardware"
)

func TestFoo(t *testing.T) {
        if err := os.Setenv("TINKERBELL_GRPC_AUTHORITY", "10.17.3.2:42113"); err != nil {
                t.Fatalf("setting TINKERBELL_GRPC_AUTHORITY environment variable: %v", err)
        }

        if err := os.Setenv("TINKERBELL_CERT_URL", "http://10.17.3.2:42114/ceert"); err != nil {
                t.Fatalf("setting TINKERBELL_CERT_URL environment variable: %v", err)
        }

        conn, err := client.GetConnection()
        if err != nil {
                t.Fatalf("creating tink client: %v", err)
        }

        c := hardware.NewHardwareServiceClient(conn)

        if _, err := c.All(context.TODO(), &hardware.Empty{}); err == nil {
                t.Fatalf("bad cert url should fail")
        }
}
$ go test -v ./foo/...
=== RUN   TestFoo
--- FAIL: TestFoo (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b0 pc=0x8ce1b7]

goroutine 6 [running]:
testing.tRunner.func1.1(0x971040, 0xddd1e0)
        /usr/lib/go/src/testing/testing.go:1076 +0x30d
testing.tRunner.func1(0xc00029c180)
        /usr/lib/go/src/testing/testing.go:1079 +0x41a
panic(0x971040, 0xddd1e0)
        /usr/lib/go/src/runtime/panic.go:969 +0x175
google.golang.org/grpc.(*ClientConn).NewStream(0x0, 0xabfce0, 0xc000024188, 0xde5a20, 0xa309fd, 0x3f, 0x0, 0x0, 0x0, 0xc000308120, ...)
        /home/invidian/go/pkg/mod/google.golang.org/grpc@v1.32.0/stream.go:145 +0x37
github.com/tinkerbell/tink/protos/hardware.(*hardwareServiceClient).All(0xc000314010, 0xabfce0, 0xc000024188, 0xc000304080, 0x0, 0x0, 0x0, 0x31b2f5dd2e8d0, 0xa702a3c, 0xa702a3c0000000f, ...)
        /home/invidian/go/pkg/mod/github.com/tinkerbell/tink@v0.0.0-20200930194128-08601fea303b/protos/hardware/hardware.pb.go:824 +0xb5
github.com/kinvolk/terraform-provider-tinkerbell/foo.TestFoo(0xc00029c180)
        /home/invidian/repos/kinvolk/terraform-provider-tinkerbell/foo/foo_test.go:28 +0x279
testing.tRunner(0xc00029c180, 0xa3b0c8)
        /usr/lib/go/src/testing/testing.go:1127 +0xef
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1178 +0x386
FAIL    github.com/kinvolk/terraform-provider-tinkerbell/foo    0.007s
FAIL
```

Notice `TINKERBELL_CERT_URL` using `ceert` instead of correct `cert`, which works as expected (as set address has running Tink instance.

**Comment by mmlb** [comment]
this will go away soon as the TINKERBELL_CERT_URL will just go away on its own.
