### ISSUE TITLE
[Tink CLI] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/tink#561]
Pushing a partial hardware json config will cause the `tink hardware list` command to panic. The `tink hardware push --file hw.json` command succeeds without complaint, but the `tink hardware list` and `tink hardware get` commands will panic.
```bash
# tink hardware list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa63898]

goroutine 1 [running]:
github.com/tinkerbell/tink/cmd/tink-cli/cmd/hardware.listHardware()
	/home/runner/work/tink/tink/cmd/tink-cli/cmd/hardware/list.go:54 +0x2a8
github.com/tinkerbell/tink/cmd/tink-cli/cmd/hardware.NewListCmd.func1(0xc0002fd680, 0x1391660, 0x0, 0x0)
	/home/runner/work/tink/tink/cmd/tink-cli/cmd/hardware/list.go:33 +0x123
github.com/spf13/cobra.(*Command).execute(0xc0002fd680, 0x1391660, 0x0, 0x0, 0xc0002fd680, 0x1391660)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1350280, 0xc0005bfef0, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x35a
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/tinkerbell/tink/cmd/tink-cli/cmd.Execute(0xdb40c8, 0x7, 0xcb6655, 0x1a)
	/home/runner/work/tink/tink/cmd/tink-cli/cmd/root.go:37 +0x126
main.main()
	/home/runner/work/tink/tink/cmd/tink-cli/main.go:19 +0xa3
```
Partial hardware config:
```JSON
{
  "id": "0eba0bf8-3772-4b4a-ab9f-6ebe93b90a97",
  "network": {
    "interfaces": [
      {
        "dhcp": {
          "mac": "52:54:00:be:a9:73"
        },
        "netboot": {
          "allow_pxe": true
        }
      }
    ]
  }
}
```

## Expected Behaviour

Either the partial hardware is rejected from a push or the `tink hardware list` is updated to accommodate partial configs.

## Current Behaviour

See above.

## Possible Solution

Workaround: update the hardware json with a "minimal" amount of data. Use the data from tinkerbell.org [here](https://docs.tinkerbell.org/hardware-data/#the-minimal-hardware-data)

## Steps to Reproduce (for bugs)

1. Follow the [Sandbox with Vagrant and Virtualbox quickstart](https://github.com/tinkerbell/sandbox/blob/main/docs/quickstarts/VAGRANTVBOX.md)
2. login to the provisioner VM: `vagrant ssh provisioner`
3. drop into the tink-cli container: `docker exec -it compose_tink-cli_1 sh`
4. Create a partial hardware json file
```bash
{
  "id": "0eba0bf8-3772-4b4a-ab9f-6ebe93b90a97",
  "network": {
    "interfaces": [
      {
        "dhcp": {
          "mac": "52:54:00:be:a9:73"
        },
        "netboot": {
          "allow_pxe": true
        }
      }
    ]
  }
}
```
5. Create the hardware record in tink: `tink hardware push --file hw.json`
6. Run `tink hardware list` or `tink hardware get`

## Context

Can't interact with hardware anymore.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
MacOS/Linux

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
[Sandbox with Vagrant and Virtualbox](https://github.com/tinkerbell/sandbox/blob/main/docs/quickstarts/VAGRANTVBOX.md) at commit [a7110f26d3e0fc2f0a81818b7792405e00070e43](https://github.com/tinkerbell/sandbox/tree/a7110f26d3e0fc2f0a81818b7792405e00070e43)
Tink server at version `quay.io/tinkerbell/tink:sha-3743d31e`.
Tink cli at version `quay.io/tinkerbell/tink-cli:sha-3743d31e`.

* Link to your project or a code example to reproduce issue:

**Comment by jacobweinstock** [comment]
closed by https://github.com/tinkerbell/tink/pull/654
