### ISSUE TITLE
Make --help work without environment variables set

### ISSUE THREAD

**Issue by invidian** [tinkerbell/tink#68]
Currently running `tink --help` gives me not the nicest panic:
```
$ tink --help
{"level":"panic","ts":1587130851.119304,"caller":"rollbar/rollbar.go:20","msg":"required envvar is unset","service":"github.com/tinkerbell/tink","pkg":"log","envvar":"ROLLBAR_TOKEN"}
panic: required envvar is unset

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00049e2c0, 0xc0002afd80, 0x1, 0x2)
        /home/invidian/go/pkg/mod/go.uber.org/zap@v1.7.1/zapcore/entry.go:229 +0x547
go.uber.org/zap.(*SugaredLogger).log(0xc00028c398, 0x4, 0x55873649a79c, 0x18, 0x0, 0x0, 0x0, 0xc0003dfa58, 0x2, 0x2)
        /home/invidian/go/pkg/mod/go.uber.org/zap@v1.7.1/sugar.go:234 +0x102
go.uber.org/zap.(*SugaredLogger).Panicw(...)
        /home/invidian/go/pkg/mod/go.uber.org/zap@v1.7.1/sugar.go:204
github.com/packethost/pkg/log/internal/rollbar.Setup(0xc00028c398, 0x55873649bbe5, 0x1a, 0x2)
        /home/invidian/go/pkg/mod/github.com/packethost/pkg@v0.0.0-20190410153520-e8e15f4ce770/log/internal/rollbar/rollbar.go:20 +0x44d
github.com/packethost/pkg/log.configureLogger(0xc00040a780, 0x55873649bbe5, 0x1a, 0x55873648bace, 0x4, 0x55873648b4dc, 0x3, 0x55873648c9da, 0x5)
        /home/invidian/go/pkg/mod/github.com/packethost/pkg@v0.0.0-20190410153520-e8e15f4ce770/log/log.go:39 +0x26c
github.com/packethost/pkg/log.Init(0x55873649bbe5, 0x1a, 0x558736699a00, 0xc0002b1100, 0x100, 0x30, 0x30, 0xc0003eccc0)
        /home/invidian/go/pkg/mod/github.com/packethost/pkg@v0.0.0-20190410153520-e8e15f4ce770/log/log.go:73 +0x228
main.main()
        /home/invidian/go/pkg/mod/github.com/tinkerbell/tink@v0.0.0-20200414145942-43213ee31781/main.go:17 +0x6c
```

**Comment by alexellis** [comment]
It's since changed to this even more un-actionable error:

```
root@ams1-c3:~/tink/cli/tink# ./tink  --help
2020/04/23 10:03:40 undefined TINKERBELL_CERT_URL```

**Comment by alexellis** [comment]
This code in `init()` causes the error, and should not be run unless there is a verb supplied:

```
	client.Setup()
```

cc @gauravgahlot
