### ISSUE TITLE
[Agent] agent docker runtime unit test require docker

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/tink#770]
The https://github.com/tinkerbell/tink/tree/main/internal/agent/runtime package unit tests require Docker to be installed. Do we want this to be a dependency for unit tests? Also, i have an Ubuntu 22.04 system with Docker (24.0.2) and `TestDockerImageNotPresent` is failing for me. output:

```bash
--- FAIL: TestDockerImageNotPresent (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9a05a5]

goroutine 19 [running]:
testing.tRunner.func1.2({0xa28c00, 0xfa4140})
        /nix/store/kfpv1z26wn481yv5z1vzakla8fllhggn-go-1.20.4/share/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /nix/store/kfpv1z26wn481yv5z1vzakla8fllhggn-go-1.20.4/share/go/src/testing/testing.go:1529 +0x39f
panic({0xa28c00, 0xfa4140})
        /nix/store/kfpv1z26wn481yv5z1vzakla8fllhggn-go-1.20.4/share/go/src/runtime/panic.go:884 +0x213
github.com/tinkerbell/tink/internal/agent/runtime_test.TestDockerImageNotPresent(0xc0001036c0)
        /home/tink/repos/tinkerbell/tink/internal/agent/runtime/docker_test.go:47 +0x4e5
testing.tRunner(0xc0001036c0, 0xb248a0)
        /nix/store/kfpv1z26wn481yv5z1vzakla8fllhggn-go-1.20.4/share/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /nix/store/kfpv1z26wn481yv5z1vzakla8fllhggn-go-1.20.4/share/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/tinkerbell/tink/internal/agent/runtime       0.029s
``` 
When I updated the test to output differently i get this: 

```bash
go test -timeout 30s -run ^TestDockerImageNotPresent$ github.com/tinkerbell/tink/internal/agent/runtime -race

--- FAIL: TestDockerImageNotPresent (2.04s)
    /home/tink/repos/tinkerbell/tink/internal/agent/runtime/docker_test.go:47: deleting image (sha256:9e179bacf43c4d3428d57cf459799ba0285b901945f9eccb17b6da056d3532c7): Error response from daemon: conflict: unable to delete 9e179bacf43c (cannot be forced) - image has dependent child images; deleting image (sha256:042a816809aac8d0f7d7cacac7965782ee2ecac3f21bcf9f24b1de1a7387b769): Error response from daemon: conflict: unable to delete 042a816809aa (cannot be forced) - image has dependent child images; deleting image (sha256:6b5c5e00213a401b500630fd8a03f6964f033ef0e3a6845c83e780fcd5deda5c): Error response from daemon: conflict: unable to delete 6b5c5e00213a (cannot be forced) - image has dependent child images
```
So it appears that this is dependent on the `alpine` image not being used by any started containers.

## Possible Solution

- One possible option is to make these test optional and opt in only.
- Another option is to use a different container image. `hello-world` for example.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by chrisdoherty4** [comment]
This was a trade-off for having some test coverage as noted in https://github.com/tinkerbell/tink/pull/730. We didn't create a ticket for introducing the integration test suite though.

Re the specific test issue I think we should treat it as a separate issue - and oversight for sure.
